output_file = "blocklist.txt"

sources = [
"https://www.spamhaus.org/drop/drop.txt",
"https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset",
"https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset",
"https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt",
]